# 作業 : (Kaggle)鐵達尼生存預測精簡版 
https://www.kaggle.com/c/titanic

# 作業1
* 下列A~E五個程式區塊中，哪一塊是特徵工程?

Ans : 程式區塊 C

# 作業2
* 對照程式區塊 B 與 C 的結果，請問那些欄位屬於"類別型欄位"? (回答欄位英文名稱即可) 

Ans : Name、Sex、Ticket、Cabin、Embarked

# 作業3
* 續上題，請問哪個欄位是"目標值"?

Ans : Survived

In [1]:
# 程式區塊 A
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

data_path = '../../Data/Part02/'
df_train = pd.read_csv(data_path + 'titanic_train.csv')
df_test = pd.read_csv(data_path + 'titanic_test.csv')
df_train.shape

(891, 12)

In [2]:
# 程式區塊 B
train_Y = df_train['Survived']
ids = df_test['PassengerId']
df_train = df_train.drop(['PassengerId', 'Survived'] , axis=1)
df_test = df_test.drop(['PassengerId'] , axis=1)
df = pd.concat([df_train,df_test])
df.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
# 程式區塊 C
LEncoder = LabelEncoder()
MMEncoder = MinMaxScaler()
for c in df.columns:
    df[c] = df[c].fillna(-1)
    if df[c].dtype == 'object':
        df[c] = LEncoder.fit_transform(list(df[c].values))
    df[c] = MMEncoder.fit_transform(df[c].values.reshape(-1, 1))
df.head(50)

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0.118683,1.0,0.283951,0.125,0.000000,0.775862,0.016072,0.000000,1.000000
1,0.0,0.218989,0.0,0.481481,0.125,0.000000,0.879310,0.140813,0.575269,0.333333
2,1.0,0.400459,0.0,0.333333,0.000,0.000000,0.984914,0.017387,0.000000,1.000000
3,0.0,0.323124,0.0,0.444444,0.125,0.000000,0.070043,0.105390,0.381720,1.000000
4,1.0,0.016845,1.0,0.444444,0.000,0.000000,0.699353,0.017630,0.000000,1.000000
5,1.0,0.626340,1.0,0.000000,0.000,0.000000,0.401940,0.018425,0.000000,0.666667
6,0.0,0.587289,1.0,0.679012,0.000,0.000000,0.117457,0.102980,0.881720,1.000000
7,1.0,0.699847,1.0,0.037037,0.375,0.111111,0.582974,0.043004,0.000000,1.000000
8,1.0,0.463247,0.0,0.345679,0.000,0.222222,0.514009,0.023636,0.000000,1.000000
9,0.5,0.648545,0.0,0.185185,0.125,0.000000,0.187500,0.060528,0.000000,0.333333
10,1.0,0.816998,0.0,0.061728,0.125,0.111111,0.904095,0.034481,0.994624,1.000000
11,0.0,0.101838,0.0,0.728395,0.000,0.000000,0.053879,0.053669,0.338710,1.000000
12,1.0,0.819296,1.0,0.259259,0.000,0.000000,0.789871,0.017630,0.000000,1.000000
13,1.0,0.029096,1.0,0.493827,0.125,0.555556,0.494612,0.062874,0.000000,1.000000
14,1.0,0.934916,0.0,0.185185,0.000,0.000000,0.609914,0.017249,0.000000,1.000000
15,0.5,0.408116,0.0,0.691358,0.000,0.000000,0.219828,0.033117,0.000000,1.000000
16,1.0,0.761868,1.0,0.037037,0.500,0.111111,0.710129,0.058686,0.000000,0.666667
17,0.5,0.973201,1.0,0.000000,0.000,0.000000,0.216595,0.027273,0.000000,1.000000
18,1.0,0.931853,0.0,0.395062,0.125,0.000000,0.449353,0.037013,0.000000,1.000000
19,1.0,0.581930,0.0,0.000000,0.000,0.000000,0.261853,0.016023,0.000000,0.333333
20,0.5,0.323890,1.0,0.444444,0.000,0.000000,0.196121,0.052598,0.000000,1.000000
21,0.5,0.085758,1.0,0.432099,0.000,0.000000,0.218750,0.027273,0.774194,1.000000
22,1.0,0.595712,0.0,0.197531,0.000,0.000000,0.408405,0.017589,0.000000,0.666667
23,0.0,0.850689,1.0,0.358025,0.000,0.000000,0.058190,0.071104,0.096774,1.000000
24,1.0,0.702144,0.0,0.111111,0.375,0.111111,0.582974,0.043004,0.000000,1.000000
25,1.0,0.049005,0.0,0.481481,0.125,0.555556,0.489224,0.063093,0.000000,1.000000
26,1.0,0.284074,1.0,0.000000,0.000,0.000000,0.256466,0.016023,0.000000,0.333333
27,0.0,0.309342,1.0,0.246914,0.375,0.222222,0.132543,0.514290,0.435484,1.000000
28,1.0,0.677642,0.0,0.000000,0.000,0.000000,0.414871,0.017297,0.000000,0.666667
29,1.0,0.908116,1.0,0.000000,0.000,0.000000,0.537716,0.017330,0.000000,1.000000
30,0.0,0.922665,1.0,0.506173,0.000,0.000000,0.881466,0.055950,0.000000,0.333333
31,0.0,0.866003,0.0,0.000000,0.125,0.000000,0.864224,0.287380,0.295699,0.333333
32,1.0,0.341501,0.0,0.000000,0.000,0.000000,0.427802,0.017046,0.000000,0.666667
33,0.5,0.957887,1.0,0.827160,0.000,0.000000,0.809267,0.022403,0.000000,1.000000
34,0.0,0.607198,1.0,0.358025,0.125,0.000000,0.883621,0.162022,0.000000,0.333333
35,0.0,0.424196,1.0,0.530864,0.125,0.000000,0.059267,0.103248,0.000000,1.000000
36,1.0,0.574273,1.0,0.000000,0.000,0.000000,0.293103,0.016031,0.000000,0.333333
37,1.0,0.148545,1.0,0.271605,0.000,0.000000,0.760776,0.017630,0.000000,1.000000
38,1.0,0.929556,0.0,0.234568,0.250,0.000000,0.450431,0.037013,0.000000,1.000000
39,1.0,0.660031,0.0,0.185185,0.125,0.000000,0.264009,0.023848,0.000000,0.333333
40,1.0,0.009188,0.0,0.506173,0.125,0.000000,0.748922,0.020406,0.000000,1.000000
41,0.5,0.921899,0.0,0.345679,0.125,0.000000,0.074353,0.042857,0.000000,1.000000
42,1.0,0.506891,1.0,0.000000,0.000,0.000000,0.577586,0.017330,0.000000,0.333333
43,0.5,0.519142,0.0,0.049383,0.125,0.222222,0.935345,0.082947,0.000000,0.333333
44,1.0,0.248851,0.0,0.246914,0.000,0.000000,0.413793,0.017297,0.000000,0.666667
45,1.0,0.777182,1.0,0.000000,0.000,0.000000,0.905172,0.017630,0.000000,1.000000
46,1.0,0.534456,1.0,0.000000,0.125,0.000000,0.686422,0.032143,0.000000,0.666667
47,1.0,0.676876,0.0,0.000000,0.000,0.000000,0.107759,0.017046,0.000000,0.666667
48,1.0,0.815467,1.0,0.000000,0.250,0.000000,0.275862,0.044181,0.000000,0.333333
49,1.0,0.039816,0.0,0.234568,0.125,0.000000,0.560345,0.036624,0.000000,1.000000

In [7]:
# 程式區塊 D
train_num = train_Y.shape[0]
train_X = df[:train_num]
test_X = df[train_num:]

from sklearn.linear_model import LogisticRegression
estimator = LogisticRegression()
estimator.fit(train_X, train_Y)
pred = estimator.predict(test_X)

In [8]:
# 程式區塊 E
sub = pd.DataFrame({'PassengerId': ids, 'Survived': pred})
sub.to_csv('titanic_baseline.csv', index=False)